opam-version: "2.0"
maintainer: "Robur <team@robur.coop>"
authors: ["Robur <team@robur.coop>"]
homepage: "https://github.com/robur-coop/ptt"
dev-repo: "git+https://github.com/robur-coop/ptt.git"
bug-reports: "https://github.com/robur-coop/ptt/issues"
license: "AGPL"

depends: [
  "ocaml" {>= "5.3.0"}
  "dune" {>= "3.0.0"}
  "mirage-crypto-rng-mkernel"
  "progress"
  "flux"
  "carton"
  "art"
  "encore"
  "cattery"
  "msendmail"
  "arc"
  "dmarc"
  "uspf"
  "dkim"
  "re"
  "uuidm"
  "unic" {build}
  "mfetch" {build}
  "duration" {>= "0.3.0"}
]
build: [
  [make "all"]
]
synopsis: "Unikernels for SMTP services"
pin-depends: [
  [ "zarith.dev"   "git+https://github.com/mirage/Zarith.git#df8969d9bb95cffca13e31a615189ab27ada0684" ]
  [ "mnet.dev"     "git+https://github.com/robur-coop/mnet.git#2922840708ccd42176a0a187d2d8ed1ef92c67d4" ]
  [ "mnet-dns.dev" "git+https://github.com/robur-coop/mnet.git#2922840708ccd42176a0a187d2d8ed1ef92c67d4" ]
  [ "mnet-tls.dev" "git+https://github.com/robur-coop/mnet.git#2922840708ccd42176a0a187d2d8ed1ef92c67d4" ]
  [ "unic.dev"     "git+https://github.com/robur-coop/unic.git#02fe3283c384f387e38f4f29c28688db22ad4a28" ]
  [ "uniq.dev"     "git+https://github.com/robur-coop/unic.git#02fe3283c384f387e38f4f29c28688db22ad4a28" ]
]
